### ISSUE TITLE
Unified use of data structure for pixels, coordinates, etc.

### ISSUE THREAD

**Issue by jwboth** [pmgbergen/DarIA#37]
Various data structures are used all over the place to address pairs of numbers. Here, I have in particular coordinates measures in numbers of pixels or physical coordinates. In particular, we also use tuples and lists. Sometimes also numpy arrays, but much more seldomly. 

In my opinion, tuples and lists are not useful here. It is very hard to make calculations with these, as one has to address the single components directly. I am therefore suggesting to convert all uses of "pairs of two numbers" from simple Iterables as tuples and lists to numpy arrays. This may extend to other use cases as well, I am not sure. 

If this is accepted, I can prepare a PR with an overhaul of all files.

**Comment by jwboth** [comment]
What do you think @EStorvik ?

**Comment by EStorvik** [comment]
I have no strong opinion about which type we use (lists, arrays, tuples), but I agree that a unified choice is way better than what we have right now. I just had to look up how both ROI extraction for pixel and ROI extraction for physical coordinates worked because they somehow are completely different. 

However, I think that it is very useful to have the possibility to work in physical coordinates as well and not only pixels, so we should make sure that both are maintained.

**Comment by jwboth** [comment]
I absoluetly agree. My points was rather about the data structures.

Pixels or coordinates. If we want to find the center. Simply taking np.average for instance gives the result, instead of doing the calculation by hand. And the list of use cases is and will be longer.

**Comment by jwboth** [comment]
Furthermore, some of the routines, e.g., conversion of lengths measures in pixels to lenghts measured in physical units, can be vectorized using arrays.

**Comment by jwboth** [comment]
I will then go ahead, and suggest some changes, and you can then see whether you agree.

**Comment by EStorvik** [comment]
Sounds great! I am all for it. If you want to (or already have some opinion on exactly how it should be done) you can make a PR. If you want me to do it I can also give it a go!
